### ISSUE TITLE
descargar archivo de destinos

### ISSUE THREAD

**Issue by Canx** [AlvaroMaceda/distance-calculator-php#1]
Hola Alvaro,

tío, esto mola mucho! 

Ya se que lo podría hacer a mano pero igual si has hecho todo esto ya lo has pensado...
¿No tendrás por ahí el archivo de centros CSV creado a partir de la lectura de la app de adjudicaciones?
Molaría también un script para descargar los centros, igual para el año que viene ;)

Saludos y suerte crack!

**Comment by AlvaroMaceda** [comment]
Con lo de la app de adjudicaciones, ¿te refieres al pdf con las plazas? Saqué el csv con un conversor pdf-excel online (no sé si fue [este](https://www.pdftoexcelonline.com/en/) o [este](https://www.pdftoexcel.com/)) y luego haciendo un poco de limpieza a mano.

Si hay alguna otra forma de conseguir esos datos, dímelo y lo miro.

Lo que sí tengo es el CSV con la lista de centros públicos de la comunidad valenciana con una dirección "entendible" por google. Ese fichero lo puedes usar para calcular las direcciones desde tu casa y luego cruzar los datos con un buscarv por código de centro. Ten en cuenta que algunas direcciones no las pude encontrar y puse las de la localidad:
[Direcciones de centros Comunidad Valenciana 2017](https://drive.google.com/file/d/0B2VE9etFtxHJX2VnZnV4c201anc/view?usp=sharing)

¿Te va bien eso?

**Comment by AlvaroMaceda** [comment]
Ah, y lo que tengo también es el [Adjudicator](https://github.com/AlvaroMaceda/adjudicator), para subir las plazas desde un excel a la aplicación. No lo he probado este año pero supongo que funcionará, no parecen haber cambios en la aplicación.

**Comment by Canx** [comment]
Vaya, esa hoja de cálculo me he dado cuenta (ahora) de que sí está publicada en la web:
http://www.ceice.gva.es/ca/web/centros-docentes/descarga-base-de-datos

Con eso ya se puede empezar a hacer el filtrado. Lo que es verdad que no está en hoja de cálculo es la lista de vacantes, solo 48h antes y en PDF!

Entonces es capaz el script de trabajar con esa hoja directamente? Voy a probar!

**Comment by Canx** [comment]
Sí funciona! pero me he dado cuenta de que no "afina" con los tiempos, hay muchos centros que les da el mismo tiempo, no se muy bien por qué... Igual se podría usar las columnas de latitud y longitud en la búsqueda, pero si no lo has hecho ya seguro que es por algo, verdad?

Al final lo que hice yo es calcularme a mano los tiempos de los centros con Google Maps en una hoja, lo sé, muy poco profesional pero bueno...

**Comment by Canx** [comment]
Ahora recuerdo que hace unos años alguien hizo un proyecto web similar:

http://decasaalcole.com/

https://github.com/decasaalcole/decasaalcole-web

Lo malo de estos es que va solo por código postal como origen...

**Comment by AlvaroMaceda** [comment]
Canx, con la hoja de datos de la generalitat no puedes hacerlo directamente: tienes que "construir" la dirección con una fórmula en la última columna. 

En los que dices que te da la misma dirección: ¿lo has hecho con la hoja "Direcciones de centros Comunidad Valenciana 2017" que te he enlazado antes o con la de la Generalitat? Si lo has hecho con la hoja que te he enlazado dime unas cuantas filas con las que tengas problemas y lo reviso.

**Comment by Canx** [comment]
Sí, es con la hoja de Conselleria, probaré añadiendo la dirección y te comento!

**Comment by AlvaroMaceda** [comment]
Te he puesto ya el enlace a la hoja con las direcciones... [mira arriba](https://github.com/AlvaroMaceda/distance-calculator-php/issues/1#issuecomment-316421603).

**Comment by AlvaroMaceda** [comment]
Supongo que ya te habrá ido todo bien, cierro el ticket.
